version: '3.8'
services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: build
    command: pnpm run start:dev api
    env_file:
      - ./apps/api/.env
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    container_name: api-service

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: build
    command: pnpm run start:dev users
    env_file:
      - ./apps/users/.env
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
    container_name: users-service
    
  guess-manager:
    build:
      context: .
      dockerfile: ./apps/guess-manager/Dockerfile
      target: build
    command: pnpm run start:dev guess-manager
    env_file:
      - ./apps/guess-manager/.env
    ports:
      - "3002:3002"
    volumes:
      - ./:/usr/src/app
    container_name: guess-manager-service  

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb
